const defaultRegister: TypeUser = {
    annualIncome: '',
    currency: '',
    citizenShip: '',
    division: '--Select--',
    dob: new Date(),
    email: '',
    employedAt: null,
    familyStatus: null,
    familyType: 'None',
    firstName: '',
    gender: '--Select--',
    height: '',
    highestEducation: '',
    lastName: '',
    maritalStatus: null,
    occupation: '',
    password: '',
    physicalStatus: null,
    ReadsQuran: null,
    ReligiousValues: '--Select--',
    residingCity: '',
    residingState: 'Andhra Pradesh',
    section: '--Select--',
    willingToMarryFrom: null,
    workLocation: '',
    wearsHijab: null,
    phoneNo: 0,
    briefNote: '',
    select: '',
    fullname: '',
};

export default defaultRegister;
