/* eslint-disable import/prefer-default-export */
export const Height = [
    '--Select--',
    '4 ft 3 inches',
    '4 ft 4 inches',
    '4 ft 5 inches',
    '4 ft 6 inches',
    '4 ft 7 inches',
    '4 ft 8 inches',
    '4 ft 9 inches',
    '4 ft 10 inches',
    '4 ft 11 inches',
    '5 ft 0 inches',
    '5 ft 1 inches',
    '5 ft 2 inches',
    '5 ft 3 inches',
    '5 ft 4 inches',
    '5 ft 5 inches',
    '5 ft 6 inches',
    '5 ft 7 inches',
    '5 ft 8 inches',
    '5 ft 9 inches',
    '5 ft 10 inches',
    '5 ft 11 inches',
    '6 ft 0 inches',
    '6 ft 1 inches',
    '6 ft 2 inches',
    '6 ft 3 inches',
    '6 ft 4 inches',
    '6 ft 5 inches',
    '6 ft 6 inches',
    '6 ft 7 inches',
    '6 ft 8 inches',
    '6 ft 9 inches',
    '6 ft 10 inches',
    '6 ft 11 inches',
];
