// import { CityProp } from 'store/slices/useRegister';

export const Occupation = [
    '-Accounting, Banking & Finance-',
    'Banking Professional',
    'Chartered Accountant',
    'Company Secretary',
    'Finance Professional',
    'Investment Professional',
    'Accounting Professional (Others)',
    '-Administration & HR-',
    'Admin Professional',
    'Human Resources Professional',
    '-Advertising, Media & Entertainment-',
    'Actor',
    'Advertising Professional',
    'Entertainment Professional',
    'Event Manager',
    'Journalist',
    'Media Professional',
    'Public Relations Professional',
    '-Agriculture-',
    'Farming',
    'Horticulturist',
    'Agricultural Professional (Others)',
    '-Airline & Aviation-',
    'Air Hostess / Flight Attendant',
    'Pilot / Co-Pilot',
    'Other Airline Professional',
    '-Architecture & Design-',
    'Architect',
    'Interior Designer',
    'Landscape Architect',
    '-Artists, Animators & Web Designers-',
    'Animator',
    'Commercial Artist',
    'Web / UX Designers',
    'Artist (Others)',
    'Beauty, Fashion & Jewellery Designers',
    'Beautician',
    'Fashion Designer',
    'Hairstylist',
    'Jewellery Designer',
    'Designer (Others)',
    'Customer Support / BPO / KPO Professional',
    'Civil Services / Law Enforcement',
    'IAS / IRS / IES / IFS',
    'Indian Police Services (IPS)',
    'Law Enforcement Employee (Others)',
    '-Defense-',
    'Airforce',
    'Army',
    'Navy',
    'Defense Services (Others)',
    '-Education & Training-',
    'Lecturer',
    'Professor',
    'Research Assistant',
    'Research Scholar',
    'Teacher',
    'Training Professional (Others)',
    '-Engineering-',
    'Civil Engineer',
    'Electronics / Telecom Engineer',
    'Mechanical / Production Engineer',
    'Non IT Engineer (Others)',
    '-Hotel & Hospitality-',
    'Chef / Sommelier / Food Critic',
    'Catering Professional',
    'Hotel & Hospitality Professional (Others)',
    'IT & Software Engineering',
    'Software Developer / Programmer',
    'Software Consultant',
    'Hardware & Networking professional',
    'Software Professional (Others)',
    '-Legal-',
    'Lawyer',
    'Legal Assistant',
    'Legal Professional (Others)',
    'Medical & Healthcare',
    'Dentist',
    'Doctor',
    'Medical Transcriptionist',
    'Nurse',
    'Pharmacist',
    'Physician Assistant',
    'Physiotherapist / Occupational Therapist',
    'Psychologist',
    'Surgeon',
    'Veterinary Doctor',
    'Therapist (Others)',
    'Medical / Healthcare Professional (Others)',
    'Merchant Navy',
    'Merchant Naval Officer',
    'Mariner',
    'Sales & Marketing',
    'Marketing Professional',
    'Sales Professional',
    '-Science-',
    'Biologist / Botanist',
    'Physicist',
    'Science Professional (Others)',
    '-Corporate Professionals-',
    'CxO / Chairman / Director / President',
    'VP / AVP / GM / DGM',
    'Sr. Manager / Manager',
    'Consultant / Supervisor / Team Leads',
    'Team Member / Staff',
    '-Others-',
    'Agent / Broker / Trader / Contractor',
    'Business Owner / Entrepreneur',
    'Politician',
    'Social Worker / Volunteer / NGO',
    'Sportsman',
    'Travel & Transport Professional',
    'Writer',
    '-Non Working-',
    'Student',
    'Retired',
    'Not working',
];

/* eslint-disable import/prefer-default-export */
export const Education = [
    '-ENGINEERING-',
    'B.E / B.Tech',
    'M.E / M.Tech',
    'M.S Engineering',
    'B.Eng (Hons)',
    'M.Eng (Hons)',
    'Engineering Diploma',
    'AE',
    'AET',
    '-ARTS / DESIGN-',
    'B.A',
    'B.Ed',
    'BJMC',
    'BFA',
    'B.Arch',
    'B.Des',
    'BMM',
    'MFA',
    'M.Ed',
    'MSW',
    'MJMC',
    'M.Arch',
    'M.Des',
    'BA (Hons)',
    'B.Arch (Hons)',
    'DFA',
    'D.Arch',
    'AA',
    'AFA',
    '-FINANCE / COMMERCE-',
    'B.Com',
    'CA / CPA',
    'CFA',
    'CS',
    'BSc / BFin',
    'M.Com',
    'MSc / MFin / MS',
    'BCom (Hons)',
    'PGD Finance',
    '-COMPUTERS / IT-',
    'BCA',
    'B.IT',
    'BCS',
    'BA Computer Science',
    'MCA',
    'PGDCA',
    'IT Diploma',
    'ADIT',
    '-SCIENCE-',
    'B.Sc',
    'M.Sc',
    'BSc (Hons)',
];

export const Currency = [
    '-Select-',
    'USD',
    'EUR',
    'JPY',
    'GBP',
    'AUD',
    'CAD',
    'CHF',
    'CNY',
    'HKD',
    'NZD',
    'SEK',
    'KRW',
    'SGD',
    'NOK',
    'MXN',
    'INR',
    'RUB',
    'ZAR',
    'TRY',
    'BRL',
    'TWD',
    'DKK',
    'PLN',
    'THB',
    'IDR',
    'HUF',
    'CZK',
    'ILS',
    'CLP',
    'PHP',
    'AED',
    'COP',
    'SAR',
    'MYR',
    'RON',
];

export const AnnualIncome = [
    '-Select-',
    'Upto INR 1 Lakh',
    'INR 1 Lakh to 2 Lakh',
    'INR 2 Lakh to 4 Lakh',
    'INR 4 Lakh to 7 Lakh',
    'INR 7 Lakh to 10 Lakh',
    'INR 10 Lakh to 15 Lakh',
    'INR 15 Lakh to 20 Lakh',
    'INR 20 Lakh to 30 Lakh',
    'INR 30 Lakh to 50 Lakh',
    'INR 50 Lakh to 75 Lakh',
    'INR 75 Lakh to 1 Crore',
    'INR 1 Crore & above',
    'Not applicable',
];

export const ResidingState = [
    'Arunachal Pradesh',
    'Assam',
    'Andhra Pradesh',
    'Bihar',
    'Chhattisgarh',
    'Dadra and Nagar Haveli',
    'Daman and Diu',
    'Delhi',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jammu and Kashmir',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Orissa',
    'Pondicherry Puduche',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
];
