/* eslint-disable import/prefer-default-export */
export const Division = [
    'Alavi-Bohra',
    'Abbasi',
    'Arab',
    'Assamese Muslims',
    'Attar',
    'Bagwan',
    'Baloch',
    'Bangladeshi',
    'Beary',
    'Bhat',
    'Bohra-others',
    'Chippa',
    'Choudary',
    'Dawoodi-Bohra',
    'Dawoodi/Idrisi Sheikh',
    'Dhobi',
    'Farooqui',
    'Gada',
    'Gadri Ghosi, Gaddi',
    'Ganchi',
    'Gujar',
    'Hashmi',
    'Iraqi Kalal',
    'Kamboj',
    'Khatri',
    'Khotta',
    'Konkani',
    'Kulhaiya',
    'Laskar',
    'Muslim-Ansari',
    'Muslim-Arain',
    'Muslim-Awan',
    'Muslim-Dakhini',
    'Muslim-Dudekula',
    'Muslim-Jat',
    'Muslim-Khoja',
    'Muslim-Labbay',
    'Muslim-Mappila',
    'Muslim-Marakayiar',
    'Muslim-Memon',
    'Muslim-Pathan',
    'Muslim-Qureshi',
    'Muslim-Rajput',
    'Muslim-Rowther',
    'Muslim-Sheikh',
    'Muslim-Siddiqui',
    'Muslim-Syed',
    'Malik',
    'Manihar',
    'Mansoori/Pinjara',
    'Meitei/Pangals',
    'Meo',
    'Molla',
    'Munshi',
    'Nagori',
    'NashyaSheikh',
];

/* eslint-disable import/prefer-default-export */
export const Section = [
    'Ansari',
    'Arain',
    'Awan',
    'Bengali',
    'Dawoodi Bohra',
    'Dekkani',
    'Dudekula',
    'Jat',
    'Khoja',
    'Lebbai',
    'Mapila',
    'Maraicar',
    'Memon',
    'Mughal',
    'Pathan',
    'Qureshi',
    'Rajput',
    'Rowther',
    'Shafi',
    'Sheikh',
    'Shia',
    'Shia Bohra',
    'Shia Imami Ismaili',
    'Shia Ithna ashariyyah',
];

export const Gender = ['Male', 'Female'];
