export interface CityProp {
    'Andhra Pradesh': string[];
    'Arunachal Pradesh': string[];
    Assam: string[];
    Bihar: string[];
    Chhattisgarh: string[];
    'Dadra and Nagar Haveli': string[];
    'Daman and Diu': string[];
    Delhi: string[];
    Goa: string[];
    Gujarat: string[];
    Haryana: string[];
    'Himachal Pradesh': string[];
    'Jammu and Kashmir': string[];
    Jharkhand: string[];
    Karnataka: string[];
    Kerala: string[];
    'Madhya Pradesh': string[];
    Maharashtra: string[];
    Manipur: string[];
    Meghalaya: string[];
    Mizoram: string[];
    Nagaland: string[];
    Orissa: string[];
    'Pondicherry Puduche': string[];
    Punjab: string[];
    Rajasthan: string[];
    Sikkim: string[];
    'Tamil Nadu': string[];
    Tripura: string[];
    'Uttar Pradesh': string[];
    Uttarakhand: string[];
    'West Bengal': string[];
}
