/* eslint-disable import/prefer-default-export */
export const countries = [
    'India',
    'USA',
    'UK',
    'Canada',
    'Australia',
    'New Zealad',
    'South  Afria',
    'Germany',
    'France',
    'Italy',
    'Spain',
    'Netherlands',
    'Sweden',
    'Norway',
    'Denmark',
    'Finland',
    'Iceland',
    'Switzerland',
    'Austria',
    'Belgium',
    'Luxembourg',
    'Portugal',
    'Greece',
    'Ireland',
    'Poland',
];
