const defaultRegister: TypeUser = {
    annualIncome: 0,
    citizenShip: '',
    division: '',
    dob: new Date(),
    email: '',
    employedAt: null,
    familyStatus: null,
    familyType: 'None',
    firstName: '',
    gender: 'FEMALE',
    height: '',
    highestEducation: '',
    lastName: '',
    maritialStatus: null,
    occupation: '',
    password: '',
    physicalStatus: 'Normal',
    ReadsQuran: 'Never Read',
    ReligiousValues: '',
    residingCity: '',
    residingState: '',
    section: '',
    willingToMarryFrom: null,
    workLocation: '',
    wearsHijab: 'None',
};

export default defaultRegister;
