/* eslint-disable import/prefer-default-export */
export const Division = [
    '--select--',
    'Alavi-Bohra',
    'Abbasi',
    'Arab',
    'Assamese Muslims',
    'Attar',
    'Bagwan',
    'Baloch',
    'Bangladeshi',
    'Beary',
    'Bhat',
    'Bohra-others',
    'Chippa',
    'Choudary',
    'Dawoodi-Bohra',
    'Dawoodi/Idrisi Sheikh',
    'Dhobi',
    'Farooqui',
    'Gada',
    'Gadri Ghosi, Gaddi',
    'Ganchi',
    'Gujar',
    'Hashmi',
    'Iraqi Kalal',
    'Kamboj',
    'Khatri',
    'Khotta',
    'Konkani',
    'Kulhaiya',
    'Laskar',
    'Muslim-Ansari',
    'Muslim-Arain',
    'Muslim-Awan',
    'Muslim-Dakhini',
    'Muslim-Dudekula',
    'Muslim-Jat',
    'Muslim-Khoja',
    'Muslim-Labbay',
    'Muslim-Mappila',
    'Muslim-Marakayiar',
    'Muslim-Memon',
    'Muslim-Pathan',
    'Muslim-Qureshi',
    'Muslim-Rajput',
    'Muslim-Rowther',
    'Muslim-Sheikh',
    'Muslim-Siddiqui',
    'Muslim-Syed',
    'Malik',
    'Manihar',
    'Mansoori/Pinjara',
    'Meitei/Pangals',
    'Meo',
    'Molla',
    'Munshi',
    'Nagori',
    'NashyaSheikh',
];
