/* eslint-disable import/prefer-default-export */
export const Education = [
    '--Select--',
    '-ENGINEERING-',
    'B.E / B.Tech',
    'M.E / M.Tech',
    'M.S Engineering',
    'B.Eng (Hons)',
    'M.Eng (Hons)',
    'Engineering Diploma',
    'AE',
    'AET',
    '-ARTS / DESIGN-',
    'B.A',
    'B.Ed',
    'BJMC',
    'BFA',
    'B.Arch',
    'B.Des',
    'BMM',
    'MFA',
    'M.Ed',
    'MSW',
    'MJMC',
    'M.Arch',
    'M.Des',
    'BA (Hons)',
    'B.Arch (Hons)',
    'DFA',
    'D.Arch',
    'AA',
    'AFA',
    '-FINANCE / COMMERCE-',
    'B.Com',
    'CA / CPA',
    'CFA',
    'CS',
    'BSc / BFin',
    'M.Com',
    'MSc / MFin / MS',
    'BCom (Hons)',
    'PGD Finance',
    '-COMPUTERS / IT-',
    'BCA',
    'B.IT',
    'BCS',
    'BA Computer Science',
    'MCA',
    'PGDCA',
    'IT Diploma',
    'ADIT',
    '-SCIENCE-',
    'B.Sc',
    'M.Sc',
    'BSc (Hons)',
];
