/* eslint-disable import/prefer-default-export */
export const FeaturedCardMenDetails = [
    {
        img: '/images/img-6.jpg',
        name: 'Ahmed Raza',
        age: 23,
        height: 5.3,
        graduation: 'Electronics Engineer',
        place: 'Bengaluru, India.',
    },
    {
        img: '/images/img-1.jpeg',
        name: 'Ahmed Raza',
        age: 23,
        height: 5.3,
        graduation: 'Electronics Engineer',
        place: 'Bengaluru, India.',
    },
    {
        img: '/images/img-5.jpeg',
        name: 'Ahmed Raza',
        age: 23,
        height: 5.3,
        graduation: 'Electronics Engineer',
        place: 'Bengaluru, India.',
    },
    {
        img: '/images/img-4.jpg',
        name: 'Ahmed Raza',
        age: 23,
        height: 5.3,
        graduation: 'Electronics Engineer',
        place: 'Bengaluru, India.',
    },
    {
        img: '/images/img-4.jpg',
        name: 'Ahmed Raza',
        age: 23,
        height: 5.3,
        graduation: 'Electronics Engineer',
        place: 'Bengaluru, India.',
    },
    {
        img: '/images/img-4.jpg',
        name: 'Ahmed Raza',
        age: 23,
        height: 5.3,
        graduation: 'Electronics Engineer',
        place: 'Bengaluru, India.',
    },
    {
        img: '/images/img-4.jpg',
        name: 'Ahmed Raza',
        age: 23,
        height: 5.3,
        graduation: 'Electronics Engineer',
        place: 'Bengaluru, India.',
    },
];
