const Occupation = [
    '--Select--',
    '-Accounting, Banking & Finance-',
    'Banking Professional',
    'Chartered Accountant',
    'Company Secretary',
    'Finance Professional',
    'Investment Professional',
    'Accounting Professional (Others)',
    '-Administration & HR-',
    'Admin Professional',
    'Human Resources Professional',
    '-Advertising, Media & Entertainment-',
    'Actor',
    'Advertising Professional',
    'Entertainment Professional',
    'Event Manager',
    'Journalist',
    'Media Professional',
    'Public Relations Professional',
    '-Agriculture-',
    'Farming',
    'Horticulturist',
    'Agricultural Professional (Others)',
    '-Airline & Aviation-',
    'Air Hostess / Flight Attendant',
    'Pilot / Co-Pilot',
    'Other Airline Professional',
    '-Architecture & Design-',
    'Architect',
    'Interior Designer',
    'Landscape Architect',
    '-Artists, Animators & Web Designers-',
    'Animator',
    'Commercial Artist',
    'Web / UX Designers',
    'Artist (Others)',
    'Beauty, Fashion & Jewellery Designers',
    'Beautician',
    'Fashion Designer',
    'Hairstylist',
    'Jewellery Designer',
    'Designer (Others)',
    'Customer Support / BPO / KPO Professional',
    'Civil Services / Law Enforcement',
    'IAS / IRS / IES / IFS',
    'Indian Police Services (IPS)',
    'Law Enforcement Employee (Others)',
    '-Defense-',
    'Airforce',
    'Army',
    'Navy',
    'Defense Services (Others)',
    '-Education & Training-',
    'Lecturer',
    'Professor',
    'Research Assistant',
    'Research Scholar',
    'Teacher',
    'Training Professional (Others)',
    '-Engineering-',
    'Civil Engineer',
    'Electronics / Telecom Engineer',
    'Mechanical / Production Engineer',
    'Non IT Engineer (Others)',
    '-Hotel & Hospitality-',
    'Chef / Sommelier / Food Critic',
    'Catering Professional',
    'Hotel & Hospitality Professional (Others)',
    'IT & Software Engineering',
    'Software Developer / Programmer',
    'Software Consultant',
    'Hardware & Networking professional',
    'Software Professional (Others)',
    '-Legal-',
    'Lawyer',
    'Legal Assistant',
    'Legal Professional (Others)',
    'Medical & Healthcare',
    'Dentist',
    'Doctor',
    'Medical Transcriptionist',
    'Nurse',
    'Pharmacist',
    'Physician Assistant',
    'Physiotherapist / Occupational Therapist',
    'Psychologist',
    'Surgeon',
    'Veterinary Doctor',
    'Therapist (Others)',
    'Medical / Healthcare Professional (Others)',
    'Merchant Navy',
    'Merchant Naval Officer',
    'Mariner',
    'Sales & Marketing',
    'Marketing Professional',
    'Sales Professional',
    '-Science-',
    'Biologist / Botanist',
    'Physicist',
    'Science Professional (Others)',
    '-Corporate Professionals-',
    'CxO / Chairman / Director / President',
    'VP / AVP / GM / DGM',
    'Sr. Manager / Manager',
    'Consultant / Supervisor / Team Leads',
    'Team Member / Staff',
    '-Others-',
    'Agent / Broker / Trader / Contractor',
    'Business Owner / Entrepreneur',
    'Politician',
    'Social Worker / Volunteer / NGO',
    'Sportsman',
    'Travel & Transport Professional',
    'Writer',
    '-Non Working-',
    'Student',
    'Retired',
    'Not working',
];

export default Occupation;
