/* eslint-disable import/prefer-default-export */
export const Section = [
    'Ansari',
    'Arain',
    'Awan',
    'Bengali',
    'Dawoodi Bohra',
    'Dekkani',
    'Dudekula',
    'Jat',
    'Khoja',
    'Lebbai',
    'Mapila',
    'Maraicar',
    'Memon',
    'Mughal',
    'Pathan',
    'Qureshi',
    'Rajput',
    'Rowther',
    'Shafi',
    'Sheikh',
    'Shia',
    'Shia Bohra',
    'Shia Imami Ismaili',
    'Shia Ithna ashariyyah',
];
